#pragma once

#include <vulkan/vulkan.h>
#include <assert.h>
#include "../Core/Expected.hpp"

namespace Acamarachi::Vulkan
{

    enum class VulkanError
    {
        NOT_READY,
        TIMEOUT,
        EVENT_SET,
        EVENT_RESET,
        INCOMPLETE,
        ERROR_OUT_OF_HOST_MEMORY,
        ERROR_OUT_OF_DEVICE_MEMORY,
        ERROR_INITIALIZATION_FAILED,
        ERROR_DEVICE_LOST,
        ERROR_MEMORY_MAP_FAILED,
        ERROR_LAYER_NOT_PRESENT,
        ERROR_EXTENSION_NOT_PRESENT,
        ERROR_FEATURE_NOT_PRESENT,
        ERROR_INCOMPATIBLE_DRIVER,
        ERROR_TOO_MANY_OBJECTS,
        ERROR_FORMAT_NOT_SUPPORTED,
        ERROR_FRAGMENTED_POOL,
        ERROR_UNKNOWN,
        ERROR_OUT_OF_POOL_MEMORY,
        ERROR_INVALID_EXTERNAL_HANDLE,
        ERROR_FRAGMENTATION,
        ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS,
        PIPELINE_COMPILE_REQUIRED,
        ERROR_SURFACE_LOST_KHR,
        ERROR_NATIVE_WINDOW_IN_USE_KHR,
        SUBOPTIMAL_KHR,
        ERROR_OUT_OF_DATE_KHR,
        ERROR_INCOMPATIBLE_DISPLAY_KHR,
        ERROR_VALIDATION_FAILED_EXT,
        ERROR_INVALID_SHADER_NV,
        ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR,
        ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR,
        ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR,
        ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR,
        ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR,
        ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR,
        ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT,
        ERROR_NOT_PERMITTED_KHR,
        ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT,
        THREAD_IDLE_KHR,
        THREAD_DONE_KHR,
        OPERATION_DEFERRED_KHR,
        OPERATION_NOT_DEFERRED_KHR,
        ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR,
        ERROR_COMPRESSION_EXHAUSTED_EXT,
        INCOMPATIBLE_SHADER_BINARY_EXT,
        ERROR_OUT_OF_POOL_MEMORY_KHR,
        ERROR_INVALID_EXTERNAL_HANDLE_KHR,
        ERROR_FRAGMENTATION_EXT,
        ERROR_NOT_PERMITTED_EXT,
        ERROR_INVALID_DEVICE_ADDRESS_EXT,
        ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS_KHR,
        PIPELINE_COMPILE_REQUIRED_EXT,
        ERROR_PIPELINE_COMPILE_REQUIRED_EXT,
        ERROR_INCOMPATIBLE_SHADER_BINARY_EXT,

        NO_PHYSICAL_DEVICE_FOUND,
        FAILED_TO_FIND_UNIQUE_QUEUES,
    };

    VulkanError VkResultToVulkanError(VkResult res);

}